### ISSUE TITLE
can't bind only to one IP

### ISSUE THREAD

**Issue by iShift** [feross/bittorrent-tracker#68]
i get error if i add any ip to "server.listen(7000, "IP");" 

events.js:171
    throw TypeError('listener must be a function');
          ^
TypeError: listener must be a function
    at TypeError (<anonymous>)
    at Server.EventEmitter.once (events.js:171:11)
    at Server.listen (/home/shift/node_modules/bittorrent-tracker/server.js:112:25)
    at Object.<anonymous> (/home/shift/node_tracker/start.js:42:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by feross** [comment]
Thanks for reporting! This is supported in 3.4.0.
