### ISSUE TITLE
Port should be > 0 and < 65536

### ISSUE THREAD

**Issue by dtrackd** [feross/bittorrent-tracker#71]
Getting this error from time to time:

```
root@box:~# bittorrent-tracker -p 80 -q

dgram.js:269
    throw new RangeError('Port should be > 0 and < 65536');
    ^
RangeError: Port should be > 0 and < 65536
    at Socket.send (dgram.js:269:11)
    at /usr/lib/node_modules/bittorrent-tracker/server.js:222:14
    at Server._onRequest (/usr/lib/node_modules/bittorrent-tracker/server.js:321:5)
    at Server.onUdpRequest (/usr/lib/node_modules/bittorrent-tracker/server.js:208:8)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:441:8)
```

**Comment by feross** [comment]
Thanks for reporting! Fixed and released as 3.4.9.
